# Generated by Django 4.0 on 2022-04-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=20)),
                ('foydalanuvchisi', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Tarmoqlar',
            },
        ),
    ]
