# Generated by Django 4.0 on 2022-04-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=10)),
                ('soni', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Davlatlar',
            },
        ),
        migrations.CreateModel(
            name='Peoples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=10)),
                ('soni', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Peoples',
                'verbose_name_plural': 'Odamlar',
            },
        ),
        migrations.CreateModel(
            name='Telefonlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=10)),
                ('narxi', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Telefonlar',
                'verbose_name_plural': 'telefonlar',
            },
        ),
    ]
