# Generated by Django 4.0 on 2022-04-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_country_peoples_telefonlar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peoples',
            new_name='Humans',
        ),
        migrations.AlterModelOptions(
            name='humans',
            options={'verbose_name': 'HUmans', 'verbose_name_plural': 'Odamlar'},
        ),
    ]
