# Generated by Django 4.0 on 2022-04-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_peoples_humans_alter_humans_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humans',
            options={'verbose_name': 'Humans', 'verbose_name_plural': 'Odamlar'},
        ),
        migrations.RenameField(
            model_name='country',
            old_name='soni',
            new_name='raqami',
        ),
    ]
